version: '3.9'

volumes:
  postgres_data:
    name: postgres_data

services:

  project-db:
    image: postgres:17.4
    container_name: project-postgres-db
    env_file: ./postgres/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    env_file: ./keycloak/keycloak.env
    volumes:
      - ./themes:/opt/keycloak/themes
      - ./keycloak/:/opt/keycloak/data/import/
    ports:
      - "8442:8442"
      - "8443:8443"
      - "9000:9000"
    command:
      - start-dev
      - --import-realm
    #command: start нужна настройка https://www.keycloak.org/server/configuration#_starting_keycloak_in_production_mode
    depends_on:
      project-db:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - keycloak_network

  project-app:
    build: ./project-app
    ports:
      - "8080:8080"
      - "5050:5050"
    networks:
      - keycloak_network


networks:
  keycloak_network:
    driver: bridge