spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/project
    #username: $POSTGRES_USER
    username: project
    #password: $POSTGRES_PASSWORD
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

server:
  servlet:
    context-path: /auth
  port: 5000