version: '3.1'
services:

  project-db:
    image: project-db
    container_name: project-db
    build:
      context: db
    networks:
      project_net:
        aliases:
          - project-db
    env_file: properties.env
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: ["CMD", "pg_isready -U postgres"]

  project-app:
    image: project-app
    container_name: project-app
    build:
      context: app
    networks:
      project_net:
        aliases:
          - project-app
    depends_on:
      - project-db
    env_file: properties.env
    ports:
      - "8080:8080"
      - "8000:8000"
    healthcheck:
      timeout: 5m
      test: ["CMD", "curl", "-f" ,"http://localhost:8080/actuator/health"]
      retries: 10

networks:
  project_net: