spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/db_notification
    driverClassName: org.postgresql.Driver
  jpa:
    database: default
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: db_notification
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
