hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  connection:
    useUnicode: true
    charSet: UTF-8
    autocommit: false
    release_mode: after_transaction
  bytecode:
    use_reflection_optimizer: true
    provider: javassist
  jdbc:
    use_scrollable_resultset: false
    use_streams_for_binary: true
    fetch_size: 200
  enable_lazy_load_no_trans: true
  temp.use_jdbc_metadata_defaults: false
  jdbc.batch_size: 30
  show_sql: true
  format_sql: true
  generate_statistics: true
  use_sql_comments: false
  session.events.log: false

postgresql:
  dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
  dataSource:
    serverName: localhost
    portNumber: 5432
    user: project
    password: qwerty
  minimumIdle: 2
  maximumPoolSize: 10
  initializationFailTimeout: -1
  registerMbeans: true
  poolName: HikariPool-PROJECT

#Spring actuator props
management:
  endpoints.web.exposure.include: health,metrics,metrics-requiredMetricName,jolokia,heapdump
  endpoint.health.show-details=always: always